#!/bin/sh -e

version=13.2.0
builddir=$PWD/build

# Extra dependências no source tree
tar -xf ../gmp-*.tar.* && mv gmp-* gcc-${version}/gmp
tar -xf ../mpfr-*.tar.* && mv mpfr-* gcc-${version}/mpfr
tar -xf ../mpc-*.tar.* && mv mpc-* gcc-${version}/mpc

cd gcc-${version}
mkdir -v ../build
cd ../build

../gcc-${version}/configure \
    --prefix=/usr \
    --disable-multilib \
    --disable-bootstrap \
    --enable-languages=c,c++ \
    --with-system-zlib

make
make DESTDIR="$1" install

# LFS recomenda link simbólico
ln -svf gcc "$1/usr/bin/cc"
