#!/bin/sh -e

version=2.40
mkdir -v build
cd build

../glibc-${version}/configure \
    --prefix=/usr \
    --disable-werror \
    --enable-kernel=4.14 \
    --with-headers=/usr/include \
    libc_cv_slibdir=/usr/lib

make
make DESTDIR="$1" install

# LFS recomenda:
ln -sfv ../lib/ld-linux-x86-64.so.2 "$1/lib64"
